FROM jaspajjr/data-science-dockerfile

COPY container-entrypoint-endpoint.sh /entry/container-entrypoint.sh
RUN chmod 0755 /entry

# RUN useradd -ms /bin/bash defaultUser && adduser defaultUser sudo

COPY requirements.txt /data/requirements.txt
RUN pip install -r /data/requirements.txt

COPY endpoint /data

COPY pipeline.pkl /data
CMD [ "/bin/bash" ]
# CMD ["start"]
# ENTRYPOINT [ "/entry" ]